name: exampletreemaker
version-script: python3 setup.py -V 
version: 0
summary: Prints command line trees
description: >
        Example snap that has a simple tree printer written in Python 3.

grade: stable
confinement: strict

parts:
  treemaker:
    plugin: python
    python-version: python3
    source-type: git
    source: .

apps:
  exampletreemaker:
    command: python3 -m treemaker

