name: printtree
version-script: python3 setup.py -V 
version: 0
summary: Prints a tree
description: >
        Print a single random ascii tree to stdout.
grade: stable
confinement: strict
parts:
  treemaker:
    plugin: python
    python-version: python3
    source-type: git
    source: .
apps:
  printtree:
    command: python3 -m treemaker

